### ISSUE TITLE
Broken pagination

### ISSUE THREAD

**Issue by ghost** [CodierIO/codier-issues#14] opened 2018-08-03 21:17 UTC
I noticed that the pagination in some challenges is bad. 

Currently in the react challenge (https://codier.io/challenge/HJwykAuGm) there are 3 pages. First page has 8 elements, second has 2 elements and third page has 4. 

Some other challenges have the same problem. 

## Expected Behavior
Paginated content should display correct number of elements.

## Current Behavior
Pagination seems wonky.

## Steps to Reproduce
1. Go to https://codier.io/challenge/HJwykAuGm
2. Press NEXT.

## Environment
Newest Firefox

**Comment by kenanyusuf** [comment] 2018-08-04 15:48
Thanks or raising this issue. Looks like a regression caused by hiding 'blank' solutions to challenges. Will get this looked at ASAP.

**Comment by kenanyusuf** [comment] 2018-08-05 20:44
Fixed in latest deployment.

**Closed as completed by kenanyusuf** 2018-08-05 20:44 UTC
Labels: bug
